import type { Article } from './schema'
import { text, code, note, table, links } from './schema'

// Keep the meaning and its English translation together for these contracts.
export const authoringEnglish: Record<string, string> = {}
const t = (fr: string, en: string) => { authoringEnglish[fr] = en; return fr }
const literal = (value: string) => t(value, value)

export const authoring: Article[] = [
  {
    slug: 'mods/paquet-genere', group: 'Créer un mod',
    title: t('Générer le paquet depuis Kotlin', 'Generate the package from Kotlin'),
    description: t('Déclarer une seule fois les informations du mod et les ressources de chaque modèle.', 'Declare mod information and each model’s resources once.'),
    sections: [
      { id: 'sources', title: t('Ce que vous écrivez, ce qui est généré', 'What you write and what is generated'), blocks: [
        text(t('Vous ne maintenez plus assets/mod.txt. Le plugin compile un lecteur de déclarations à partir de vos sources Kotlin, construit le mod avec createMod puis génère le catalogue du jeu. Il ne lance pas le jeu et n’appelle ni les règles, ni les services, ni onTick. createMod et les initialiseurs doivent donc uniquement assembler des déclarations, sans accès au jeu ni écriture de fichiers.', 'You no longer maintain assets/mod.txt. The plugin compiles a declaration reader from your Kotlin sources, constructs the mod with createMod, then generates the game catalogue. It does not launch the game or call rules, services or onTick. createMod and initialisers must therefore only assemble declarations, without game access or file writes.')),
        table([t('Source', 'Source'), t('Rôle et destination', 'Purpose and destination')], [
          [literal('mod.json'), t('Identifiant, nom, version, module et compatibilité. Le Hub le lit avant compilation. Le plugin génère nimby.mod.modInfo : utilisez cette identité dans signalMod(modInfo) ou toolMod(modInfo).', 'Identity, name, version, module and compatibility. The Hub reads it before compilation. The plugin generates nimby.mod.modInfo: use that identity in signalMod(modInfo) or toolMod(modInfo).')],
          [literal('metadata(author, description, name)'), t('Auteur, description et nom affiché optionnel. name et description acceptent tr ; sans name, le nom provient de modInfo. La version complète, suffixe alpha compris, vient de mod.json.', 'Author, description and optional display name. name and description accept tr; without name, the name comes from modInfo. The complete version, including its alpha suffix, comes from mod.json.')],
          [literal('construction(states, name, kind, catalogueName)'), t('Catalogue de textures et entrée du menu de construction. Une déclaration par modèle de signal.', 'Texture catalogue and construction-menu entry. One declaration per signal model.')],
          [literal('assets/ · imgs/ · config/'), t('Fichiers copiés dans le paquet. assets/closed.svg se déclare closed.svg ; imgs/signals/closed.svg conserve ce chemin.', 'Files copied into the package. Declare assets/closed.svg as closed.svg; imgs/signals/closed.svg keeps its path.')],
          [literal('mod.txt · nrf-metadata.json · nrf-mod.ini · project.json'), t('Catalogue du jeu, traductions des métadonnées, manifeste du chargeur et manifeste du Hub. Fichiers générés : ne les éditez pas, la compilation suivante les remplacera.', 'Game catalogue, metadata translations, loader manifest and Hub manifest. These are generated files: do not edit them, as the next build replaces them.')],
        ]),
        code('import nimby.*\nimport nimby.mod.modInfo\n\nfun createMod() = signalMod(modInfo) {\n    metadata(author = "Votre nom", description = "Mes signaux personnalisés.")\n    signal(firstSignal)\n}', t('Assembler le mod', 'Assemble the mod')),
        note(t('Cette génération exige le kit contenant ModResources et bridge/Package.kt. Un ancien kit ne suffit pas. Un outil utilise aussi metadata, mais ne déclare aucun signal fictif.', 'Generation requires the kit containing ModResources and bridge/Package.kt. An older kit is not sufficient. A tool also uses metadata, but declares no fictitious signal.')),
      ] },
      { id: 'construction', title: t('Paramètres du catalogue', 'Catalogue parameters'), blocks: [
        code('construction(\n    states = listOf("closed.svg", "open.svg"),\n    name = "Mon signal",\n    kind = "path"\n)', t('Dans le bloc signalModel', 'Inside the signalModel block')),
        table([t('Paramètre', 'Parameter'), t('Utilisation précise', 'Exact use')], [
          [literal('states: List<String>'), t('De 1 à 256 images dans leur ordre définitif. Le SDK ne devine pas les chemins retournés par images ou appearance. Déclarez aussi les deux images de chaque clignotement.', 'Between 1 and 256 images in their permanent order. The SDK does not guess paths returned by images or appearance. Also declare both images of each blinking animation.')],
          [literal('name: String'), t('Nom dans le menu de construction. Par défaut, le titre du modèle. Accepte un texte ou tr : la génération résout l’anglais puis la langue de repli du JSON.', 'Name in the construction menu. Defaults to the model title. Accepts plain text or tr: generation resolves English, then the JSON fallback language.')],
          [literal('kind: String = "path"'), t('Type natif du signal, écrit dans SignalTemplate. path est utilisé pour nos signaux. Ce champ ne décide ni indication ni vitesse ; un autre type exige de vérifier sa prise en charge dans le jeu.', 'Native signal kind, written into SignalTemplate. Our signals use path. This field decides neither indication nor speed; another kind requires checking game support.')],
          [literal('catalogueName: String = name'), t('Nom du jeu de textures dans les choix natifs du jeu ; peut différer du nom du signal constructible.', 'Texture-set name in the game’s native selectors; it may differ from the constructible signal name.')],
          [literal('nameKey / catalogueNameKey: String?'), t('Clés name_loc natives pour préserver un ancien catalogue. Avec tr(...) dans name ou catalogueName, laissez la clé correspondante à null : le SDK la génère. Les deux mécanismes ne se combinent pas pour le même nom.', 'Native name_loc keys for preserving an old catalogue. When using tr(...) in name or catalogueName, leave its corresponding key null: the SDK generates it. The two mechanisms cannot be combined for the same name.')],
        ]),
        note(t('Utilisez tr(...) pour les noms constructibles, les noms de catalogues, les titres de panneaux et les descriptions. Le plugin génère name_en comme repli lisible et les clés name_loc du SDK pour suivre la langue du jeu. Le même catalogue JSON alimente aussi les noms des ressources dans la fiche du mod en partie. Les identifiants ne doivent jamais être traduits.', 'Use tr(...) for construction names, catalogue names, panel titles and descriptions. The plugin generates name_en as a readable fallback and SDK name_loc keys that follow the game language. The same JSON catalogue also supplies resource names in the in-game mod details. Identifiers must never be translated.')),
        text(t('Conservez textureSet et l’ordre des states d’un catalogue publié, y compris les anciennes images encore référencées par une sauvegarde. Un changement de fichier à un indice existant change l’apparence correspondante ; réordonner les indices peut attribuer la mauvaise image aux signaux déjà posés.', 'Keep textureSet and the states order of a published catalogue, including old images still referenced by saves. Changing a file at an existing index changes that appearance; reordering indices can assign the wrong image to existing signals.')),
      ] },
      { id: 'verifier', title: t('Compiler et vérifier le résultat', 'Build and inspect the result'), blocks: [
        code('.\\gradlew.bat generateDebugGameManifest\n.\\gradlew.bat windowsTest packageMod', t('Commandes du projet', 'Project commands'), 'powershell'),
        text(t('Le fichier généré se trouve dans build/gradle/generated/game/debug/mod.txt ou release/mod.txt. Le paquet assemblé contient son mod.txt à la racine. Les tests natifs reçoivent aussi le catalogue généré. Un fichier manquant, un chemin hors du paquet, une ressource ambiguë, un catalogue dupliqué ou un ancien assets/mod.txt bloque la compilation.', 'The generated file is in build/gradle/generated/game/debug/mod.txt or release/mod.txt. The assembled package contains mod.txt at its root. Native tests also receive the generated catalogue. A missing file, an out-of-package path, an ambiguous resource, a duplicate catalogue or an old assets/mod.txt blocks the build.')),
        text(t('Pour convertir un projet existant, recopiez l’auteur et la description dans metadata et chaque liste state dans construction, en conservant exactement les identifiants et l’ordre. Supprimez ensuite assets/mod.txt et comparez le catalogue généré à l’ancien avant installation.', 'To convert an existing project, move the author and description into metadata and each state list into construction, preserving identifiers and order exactly. Then remove assets/mod.txt and compare the generated catalogue with the previous one before installation.')),
        links({label: t('Construire son premier mod', 'Build your first mod'), to: '/commencer/premier-mod'}, {label: t('Référence ModResources', 'ModResources reference'), to:'/reference/modresources'}),
      ] },
    ],
  },
  {
    slug: 'mods/interface', group: 'Créer un mod',
    title: t('Où apparaissent les textes et les contrôles ?', 'Where do text and controls appear?'),
    description: t('Cases, titres, boutons, champs et messages : leur emplacement, leur durée de vie et leurs événements.', 'Checkboxes, titles, buttons, fields and messages: location, lifetime and events.'),
    sections: [
      {id:'signal',title:t('Panneau du signal sélectionné', 'Selected signal panel'),blocks:[
        text(t('Le SDK ajoute les réglages sous les propriétés natives du signal sélectionné, dans un groupe défilant. Les réglages de chaque modèle sont séparés des commandes d’outils. Les longs libellés peuvent défiler horizontalement ; les aides reviennent à la ligne. L’ordre des cases suit la déclaration Kotlin.', 'The SDK adds settings below the selected signal’s native properties, in a scrolling group. Model settings are separated from tool commands. Long labels can scroll horizontally; help text wraps. Checkbox order follows the Kotlin declaration.')),
        code('val automatic = checkbox(\n    name = "automatic",\n    label = tr("automatic.label"),\n    description = tr("automatic.help"),\n    defaultValue = true\n)\nrules {\n    if (!enabled(automatic)) Indication(Aspect.Closed, Reason.Disabled)\n    else /* votre décision à partir des observations */ null\n}'),
        table([t('Champ', 'Field'), t('Emplacement et effet', 'Location and effect')],[
          [literal('SignalType.title'),t('Titre au-dessus des cases de ce modèle. Accepte tr. Ce n’est pas automatiquement le nom du menu de construction : celui-ci vient de construction.name.', 'Heading above this model’s checkboxes. Accepts tr. It is not automatically the construction-menu name, which comes from construction.name.')],
          [literal('Checkbox.name'),t('Clé technique enregistrée pour chaque signal posé. Invisible pour le joueur. Ne la renommez pas selon la langue.', 'Technical key saved for each placed signal. Invisible to the player. Do not rename it according to the language.')],
          [literal('Checkbox.label'),t('Texte à côté de la case. Accepte tr.', 'Text next to the checkbox. Accepts tr.')],
          [literal('Checkbox.description'),t('Texte d’aide sous la case, avec retour à la ligne. Accepte tr. Une chaîne vide ne crée aucune ligne. Il est visible directement, sans survol.', 'Help text below the checkbox, with word wrapping. Accepts tr. An empty string creates no row. It is directly visible, without hovering.')],
          [literal('Checkbox.defaultValue'),t('Valeur utilisée avant tout réglage enregistré pour ce signal. Elle ne remplace pas une valeur déjà sauvegardée.', 'Value used before any setting has been saved for this signal. It does not replace an existing saved value.')],
          [literal('Checkbox.onlyWhenEnabled'),t('Si true, la case est présentée uniquement tant que sa valeur est vraie. Utile pour un acquittement ; une fois décochée, elle disparaît. Laisser false pour un réglage ordinaire.', 'If true, the checkbox is shown only while its value is true. Useful for acknowledgement; once unchecked, it disappears. Leave false for a normal setting.')],
          [literal('enabled(option) / settingsStatus'),t('Vos règles consultent la case ; le SDK ne choisit aucune conséquence. Absent utilise les défauts ; Unavailable rend l’observation non fraîche.', 'Your rules read the checkbox; the SDK chooses no consequence. Absent uses defaults; Unavailable makes the observation stale.')],
        ]),
      ]},
      {id:'outils',title:t('Actions et panneaux d’outils', 'Actions and tool panels'),blocks:[
        table([t('Déclaration', 'Declaration'), t('Comportement visible et événement', 'Visible behaviour and event')],[
          [literal('SignalAction(id, label, whenMod, service)'),t('Bouton sous les réglages du signal, visible si le mod fournisseur et son service sont disponibles dans la même partie. label est affiché ; id, whenMod et service restent techniques. Aucune dépendance obligatoire entre mods.', 'Button below the signal settings, visible when the provider mod and service are available in the same game session. label is displayed; id, whenMod and service remain technical. No mandatory mod dependency.')],
          [literal('showPanel(request, message, buttons, inputs)'),t('Remplace le bouton d’origine par un panneau temporaire. message apparaît au-dessus des champs et boutons, avec retour à la ligne. Chaque republication remplace ces contrôles, sans modifier les cases persistantes.', 'Replaces the original action button with a temporary panel. message appears above the fields and buttons, with wrapping. Each publication replaces these controls without changing persistent checkboxes.')],
          [literal('ToolButton(id, label, enabled)'),t('label est le texte du bouton. enabled=false empêche son activation. Le clic arrive dans le même service, avec request.action=id et request.value=null. Jusqu’à 12 boutons.', 'label is the button text. enabled=false prevents activation. A click reaches the same service with request.action=id and request.value=null. Up to 12 buttons.')],
          [literal('ToolNumberInput(id, label, value, minimum, maximum, enabled)'),t('label est affiché au-dessus du champ entier. value est la valeur proposée ; minimum et maximum bornent les valeurs acceptées. enabled=false empêche la saisie. Une édition valide arrive avec action=id et value=nouvel entier. Jusqu’à 4 champs.', 'label appears above the integer field. value is the proposed value; minimum and maximum bound accepted values. enabled=false prevents editing. A valid edit arrives with action=id and value=the new integer. Up to 4 fields.')],
          [t('Saisie incomplète', 'Incomplete input'),t('Un champ vide, invalide ou hors bornes conserve le brouillon et bloque les commandes. Le SDK n’invente pas zéro. Après une édition valide, le mod republie le panneau et invalide son ancien aperçu.', 'An empty, invalid or out-of-range field retains its draft and blocks commands. The SDK does not invent zero. After a valid edit, the mod republishes the panel and invalidates its old preview.')],
          [literal('request.signalId / worldId / generation'),t('Source de l’action et identité de la partie. Ne réutilisez pas un ticket ou un aperçu après changement de génération. panelToken et originAction relient les clics au panneau d’origine : transmettez la requête reçue.', 'Action source and game-session identity. Do not reuse a ticket or preview after a generation change. panelToken and originAction connect clicks to the original panel: pass along the received request.')],
        ]),
        text(t('Un texte déclaré n’est pas une action automatique : écrire « Fermer » ou « Confirmer » ne ferme ni ne construit rien. Le service doit traiter l’identifiant reçu. Pour fermer, retirez l’aperçu et republiez le bouton d’ouverture ; pour construire, utilisez un ticket et suivez son résultat.', 'Declared text is not an automatic action: writing “Close” or “Confirm” does not close or build anything. The service must handle the received identifier. To close, clear the preview and republish the opening button; to build, use a ticket and track its result.')),
        links({label:t('Exemple d’outil et champs numériques', 'Tool example and numeric fields'),to:'/mods/outils-optionnels'}, {label:t('Traductions JSON', 'JSON translations'),to:'/mods/traductions'}),
      ]},
      {id:'reproduire',title:t('Reconstruire un mod complet', 'Rebuild a complete mod'),blocks:[
        text(t('Pour une signalisation comparable à SFR : assemblez plusieurs signalModel, chacun avec ses enums, règles, construction, images et driving ; ajoutez les cases propres au modèle, observez l’approche si nécessaire et lisez next avec son type. Les couleurs et les vitesses restent des choix du mod. Les extraits SFR du wiki montrent des usages ciblés sans imposer le téléchargement du projet.', 'For signalling comparable to SFR: combine multiple signalModel declarations, each with its enums, rules, construction, images and driving; add model-specific checkboxes, observe approaching trains where needed, and read next with its type. Colours and speeds remain mod choices. The wiki’s SFR excerpts illustrate focused uses without requiring the project download.')),
        text(t('Pour un outil comparable à Signal Placement : déclarez toolMod et un service facultatif ; lisez network, calculez les positions en respectant les raccordements et aiguilles, affichez toutes les positions avec showSignalPreview, puis préparez un ticket et relisez le réseau avant confirmation. Suivez Pending avec pollConstruction, utilisez undoConstruction uniquement si canUndo, et remettez à zéro votre état lors d’un changement de partie ou de onStop. Le calcul métier appartient à l’outil.', 'For a tool comparable to Signal Placement: declare toolMod and an optional service; read network, calculate positions while respecting connections and junctions, display all positions with showSignalPreview, then prepare a ticket and read the network again before confirmation. Track Pending with pollConstruction, use undoConstruction only when canUndo, and reset your state on session changes or onStop. The tool owns its domain calculations.')),
        links({label:t('Parcourir les possibilités du SDK', 'Browse SDK capabilities'),to:'/commencer/possibilites'}, {label:t('Extraits ciblés de SFR', 'Focused SFR excerpts'),to:'/mods/exemples-sfr'}, {label:t('Référence des opérations d’outils', 'Tool operations reference'),to:'/reference/toolcontext'}),
      ]},
    ],
  },
]
