import type { Article } from './schema'
import { text, code, note, table, links } from './schema'

export const toolAuthoringEnglish: Record<string, string> = {}
const t = (fr: string, en: string) => { toolAuthoringEnglish[fr] = en; return fr }
const literal = (value: string) => t(value, value)

export const toolAuthoring: Article[] = [
  {
    slug: 'maintenance/distribution', group: 'Maintenance',
    title: t('Releases, mises à jour et secours GitHub', 'Releases, updates and GitHub fallback'),
    description: t('Comment le Hub découvre les nouveautés sans intégrer de token privé.', 'How the Hub discovers updates without embedding a private token.'),
    sections: [
      {id:'decouverte',title:t('Détection automatique', 'Automatic detection'),blocks:[
        text(t('Le Hub consulte le catalogue NRF en priorité. Si le serveur est indisponible, il utilise les releases officielles de NimbyRails-France sur GitHub. Chaque dépôt publie un catalogue public dans la release technique catalogue, fichier releases.json. La vérification a lieu toutes les minutes lorsque le Hub est ouvert ; une opération en cours ou le réseau peuvent la retarder.', 'The Hub prefers the NRF catalogue. If the server is unavailable, it uses official NimbyRails-France GitHub releases. Each repository publishes a public releases.json file in the technical catalogue release. Checks run every minute while the Hub is open; an ongoing operation or network delay may postpone them.')),
        text(t('Le canal reste celui choisi pour chaque projet : Stable, Bêta ou Alpha. Une nouvelle version installable apparaît dans le catalogue ; pour un projet déjà installé, le Hub notifie une fois cette version. Le téléchargement automatique reste soumis à vos réglages et aux protections du mode développeur. La découverte ne remplace pas immédiatement les fichiers du jeu.', 'Each project keeps its selected channel: Stable, Beta or Alpha. A new installable version appears in the catalogue; for an installed project, the Hub notifies once per version. Automatic downloading remains subject to your settings and developer-mode protections. Discovery does not immediately replace game files.')),
        note(t('Aucun token de publication ne se trouve dans le Hub. Lire un catalogue public et télécharger un fichier de release ne nécessite pas le token du mainteneur. L’API GitHub sert seulement de secours aux dépôts sans catalogue disponible, avec un cache de quinze minutes, un plafond de requêtes et une pause après limitation. Le catalogue normal reste vérifié chaque minute.', 'The Hub contains no publisher token. Reading a public catalogue and downloading a release asset do not require the maintainer’s token. The GitHub API is only a fallback for repositories without an available catalogue, with a fifteen-minute cache, request cap and backoff after rate limiting. Normal catalogue checks still run every minute.')),
      ]},
      {id:'publication',title:t('Publication dans la CI', 'CI publication'),blocks:[
        text(t('Une publication Woodpecker vérifie les fichiers, prépare une release GitHub en brouillon, téléverse les fichiers puis rend la release publique. Elle met ensuite à jour le catalogue du dépôt et le miroir NRF. Les deux destinations distribuent les mêmes binaires. Les noms de projets, versions, plateformes, tailles et SHA-256 sont vérifiés avant utilisation ; un autre miroir ne permet jamais d’ignorer un contrôle.', 'A Woodpecker publication verifies files, prepares a draft GitHub release, uploads assets and then publishes the release. It subsequently updates the repository catalogue and NRF mirror. Both destinations distribute the same binaries. Project names, versions, platforms, sizes and SHA-256 hashes are checked before use; switching mirrors never bypasses a check.')),
        text(t('Le secret nrf_release_token reste dans Woodpecker, uniquement à l’étape de publication. Un build ordinaire ne publie pas. Le sujet release X.Y.Z-alpha.N, la branche alpha, VERSION et le changelog daté doivent correspondre. Une version déjà publiée ne peut pas recevoir des binaires différents : incrémentez la version. Pour un nouveau mod, activez son dépôt dans Woodpecker et référencez un SDK déjà publié contenant les API utilisées.', 'The nrf_release_token secret stays in Woodpecker, only in the publication step. Ordinary builds do not publish. The release X.Y.Z-alpha.N subject, alpha branch, VERSION and dated changelog must agree. An already published version cannot receive different binaries: increment the version. For a new mod, enable its repository in Woodpecker and pin an already published SDK containing the APIs it uses.')),
        links({label:t('Préparer les paquets', 'Prepare packages'),to:'/mods/paquet-genere'}),
      ]},
    ],
  },
  {
    slug: 'commencer/langues-applications', group: 'Commencer',
    title: t('Langues du Hub, du TCO et des mods', 'Hub, TCO and mod languages'),
    description: t('Choisir français ou anglais et comprendre quelle langue chaque interface utilise.', 'Choose French or English and understand which language each interface uses.'),
    sections: [
      {id:'choix',title:t('Choisir la langue', 'Choose the language'),blocks:[
        table([t('Interface', 'Interface'),t('Réglage', 'Setting')],[
          [literal('Hub'),t('Paramètres > Langue : Automatique (système), Français ou English. Le choix est conservé dans le profil du Hub, sans changer les installations, les canaux ou le profil Jouer/Développer.', 'Settings > Language: Automatic (system), Français or English. The choice is stored in the Hub profile without changing installations, channels or the Play/Develop profile.')],
          [literal('TCO'),t('Le sélecteur de langue est dans l’en-tête. Le choix est mémorisé sur votre ordinateur. Les libellés et détails changent sans déconnecter le SDK ni réinitialiser les filtres.', 'The language selector is in the header. Your choice is remembered on your computer. Labels and details update without disconnecting the SDK or resetting filters.')],
          [t('Mods dans NIMBY Rails', 'Mods in NIMBY Rails'),t('Ils suivent la langue du jeu, indépendamment du Hub et du TCO. Chaque mod déclare son propre fallback dans assets/translations.json.', 'They follow the game language, independently of the Hub and TCO. Each mod declares its own fallback in assets/translations.json.')],
          [t('Installateur Windows du Hub', 'Hub Windows installer'),t('Français et anglais sont disponibles dans l’assistant d’installation. Ce choix ne remplace pas une préférence déjà enregistrée dans le Hub.', 'French and English are available in the installation wizard. This choice does not replace a preference already saved in the Hub.')],
        ]),
        text(t('En mode automatique, le Hub et le TCO choisissent le français si la langue du système commence par fr ; sinon, l’anglais. Un changement de langue n’exige pas de réinstaller les projets. Les noms de trains, de lignes, de gares, les chemins et les identifiants restent ceux des données sources.', 'In automatic mode, the Hub and TCO choose French if the system language starts with fr; otherwise they choose English. Changing language does not require reinstalling projects. Train, line and station names, paths and identifiers retain their source values.')),
        note(t('Les journaux historiques restent dans la langue utilisée lors de l’opération. Les diagnostics bruts de Windows, du SDK, de Gradle ou d’un mod sont conservés tels quels pour retrouver précisément une erreur. Les noms et descriptions des projets du catalogue du Hub proviennent de leur manifeste de distribution : ils ne sont pas remplacés par le fichier de traduction destiné au jeu.', 'Historical logs remain in the language used when the operation occurred. Raw diagnostics from Windows, the SDK, Gradle or a mod are preserved exactly to help trace errors. Project names and descriptions in the Hub catalogue come from their distribution manifest: the translation file intended for the game does not replace them.')),
        links({label:t('Traduire les textes de votre mod', 'Translate your mod text'),to:'/mods/traductions'}, {label:t('Traduire les métadonnées et catalogues', 'Translate metadata and catalogues'),to:'/mods/metadonnees-traduites'}),
      ]},
    ],
  },
  {
    slug: 'mods/metadonnees-traduites', group: 'Créer un mod',
    title: t('Traduire le nom et la description du mod', 'Translate the mod name and description'),
    description: t('Un seul JSON, un mod.txt généré avec repli et une adaptation Windows pour la liste des mods.', 'One JSON file, a generated mod.txt with fallback text and a Windows adapter for the mod list.'),
    status: 'experimental',
    sections: [
      { id: 'declaration', title: t('Déclarer les textes une seule fois', 'Declare text once'), blocks: [
        code('metadata(\n    author = "Your name",\n    name = tr("mod.name"),\n    description = tr("mod.description")\n)', t('Dans signalMod ou toolMod', 'Inside signalMod or toolMod')),
        code(JSON.stringify({ fallback: 'fr', languages: {
          fr: { 'mod.name': 'Mes signaux', 'mod.description': 'Des signaux pour mon réseau.' },
          en: { 'mod.name': 'My signals', 'mod.description': 'Signals for my network.' },
        }}, null, 2), literal('assets/translations.json'), 'json'),
        text(t('Vous pouvez mélanger du texte direct et tr. author reste la signature de l’auteur. Le nom affiché est facultatif ; son absence reprend le nom du mod.json. Les références acceptent aussi les paramètres nommés de tr, résolus à la compilation. Chaque clé doit exister dans la langue fallback.', 'You can mix plain text and tr. author remains the author’s credit. The display name is optional; omitting it uses the name from mod.json. References also support tr’s named parameters, resolved at build time. Every key must exist in the fallback language.')),
        note(t('Ne traduisez jamais id, modId, module, textureSet, les identifiants de modèle, de service ou de case. Ces valeurs relient les paquets, réglages et sauvegardes ; elles ne sont pas des textes pour les joueurs.', 'Never translate id, modId, module, textureSet, or model, service and checkbox identifiers. These values connect packages, settings and saves; they are not player-facing text.')),
      ]},
      { id: 'affichage', title: t('Ce que le jeu reçoit réellement', 'What the game actually receives'), blocks: [
        table([t('Emplacement', 'Location'), t('Comportement', 'Behaviour')], [
          [literal('mod.txt'), t('Nom et description dans la langue de repli. Ce fichier reste lisible sans la passerelle ; le SDK ne le réécrit pas quand la langue change.', 'Name and description in the fallback language. The file remains readable without the bridge; the SDK does not rewrite it when the language changes.')],
          [literal('nrf-metadata.json'), t('Textes résolus pour chaque langue, générés à côté de mod.txt. Aucun second fichier à maintenir manuellement.', 'Resolved text for each language, generated alongside mod.txt. No second file needs manual maintenance.')],
          [t('Liste des mods d’une nouvelle partie', 'New-game mod list'), t('La passerelle Windows traduit le nom de liste et la fiche du sélecteur. Elle relit la langue effective du jeu ; langue exacte, langue de base, puis fallback.', 'The Windows bridge translates the list name and picker details. It reads the game’s effective language, trying the exact locale, base language, then fallback.')],
          [t('Gestionnaire de mods pendant une partie', 'In-game mod manager'), t('Le nom de liste, le titre et la description de la fiche sont adaptés au moment de leur affichage. Les métadonnées enregistrées dans la sauvegarde restent intactes.', 'The list name, details title and description are adapted as they are displayed. Metadata stored in the save remains intact.')],
          [t('Construction et contenu du mod', 'Construction and mod contents'), t('construction(name = tr(...), catalogueName = tr(...)) génère les noms traduits des signaux et catalogues de textures. Le détail des ressources du gestionnaire utilise aussi ces textes.', 'construction(name = tr(...), catalogueName = tr(...)) generates translated signal and texture catalogue names. The manager’s resource details also use this text.')],
          [t('Hub et publication Steam', 'Hub and Steam publishing'), t('Ils conservent les métadonnées de leur propre manifeste. Cette fonctionnalité ne traduit pas la page Steam ni l’interface du Hub.', 'They retain the metadata from their own manifest. This feature does not translate the Steam page or Hub interface.')],
        ]),
        note(t('La liste native ne présente que les mods contenant les ressources acceptées par le jeu. Un toolMod sans ressources, comme un outil d’horloge, est chargé par NRF Loader et peut être absent de cette liste. Générer ses métadonnées ne l’ajoute pas au sélecteur ; son interface peut utiliser tr indépendamment.', 'The native list only presents mods containing resource types accepted by the game. A toolMod without resources, such as a clock tool, is loaded by NRF Loader and may be absent from this list. Generating its metadata does not add it to the picker; its interface can use tr independently.')),
        text(t('Les descriptions peuvent contenir des retours à la ligne : la génération les encode avec le format natif <br> de ModMeta.desc. Le nom reste sur une seule ligne. Le catalogue est isolé par l’identité du mod : deux paquets peuvent utiliser les mêmes clés sans partager leurs textes.', 'Descriptions may contain line breaks: generation encodes them using ModMeta.desc’s native <br> format. Names remain single-line. Each catalogue is isolated by mod identity: two packages can use the same keys without sharing text.')),
        note(t('Adaptation en développement pour le binaire Windows reconnu : le sélecteur de nouvelle partie a été contrôlé en jeu en français puis en anglais. Le chargement de la passerelle par le proxy de production a été observé dans les journaux. Les nouvelles adaptations du gestionnaire en partie et des catalogues ont des tests autonomes ; leur affichage réel reste à vérifier. Un binaire inconnu, une passerelle absente, un JSON invalide ou différent du mod.txt conserve le texte natif de repli.', 'Development adapter for the recognised Windows executable: the new-game picker was checked in-game in French and English. Production proxy loading was observed in the logs. The new in-game manager and catalogue adapters have standalone tests; their actual rendering still requires in-game verification. An unknown binary, missing bridge, invalid JSON or mismatch with mod.txt retains native fallback text.')),
        links({label:t('Traduire les panneaux et boutons', 'Translate panels and buttons'),to:'/mods/traductions'}, {label:t('Comprendre la génération du paquet', 'Understand package generation'),to:'/mods/paquet-genere'}),
      ]},
      { id: 'catalogues', title: t('Traduire chaque modèle de signal', 'Translate each signal model'), blocks: [
        code('construction(\n    states = listOf("imgs/closed.png", "imgs/open.png"),\n    name = tr("signal.construction"),\n    catalogueName = tr("signal.catalogue")\n)', t('Dans la déclaration de votre signalModel', 'Inside your signalModel declaration')),
        code(JSON.stringify({ fallback: 'fr', languages: {
          fr: { 'signal.construction': 'Mon signal', 'signal.catalogue': 'Mes feux' },
          en: { 'signal.construction': 'My signal', 'signal.catalogue': 'My lights' },
        }}, null, 2), t('Clés à ajouter au même assets/translations.json', 'Keys to add to the same assets/translations.json'), 'json'),
        text(t('name apparaît dans le choix des signaux à construire ; catalogueName nomme leur jeu de textures, notamment dans le contenu du mod. Omettez catalogueName pour reprendre name. Une simple chaîne reste possible. Pour tr, laissez nameKey et catalogueNameKey absents : la génération crée des clés natives distinctes par mod, modèle et rôle. Plusieurs modèles peuvent donc utiliser les mêmes clés JSON dans des mods différents sans collision.', 'name appears in the signal construction choices; catalogueName names the texture set, including in mod contents. Omit catalogueName to reuse name. Plain strings are also supported. With tr, leave nameKey and catalogueNameKey unset: generation creates distinct native keys for each mod, model and role. Models in different mods can therefore reuse the same JSON keys without a collision.')),
        text(t('Le paquet contient toujours name_en en anglais, ou dans votre langue fallback si la clé anglaise manque. name_loc et le catalogue nrf-metadata.json assurent la traduction avec le SDK. Le SDK ne réécrit pas les fichiers et ne change ni les IDs, ni l’ordre des textures, ni les chemins. Reconstruisez le paquet après modification du JSON ; tous ces textes proviennent de la déclaration compilée.', 'The package always contains name_en in English, or in your fallback language if the English key is missing. name_loc and nrf-metadata.json provide translation through the SDK. The SDK does not rewrite files or change IDs, texture order or paths. Rebuild the package after editing the JSON; all of this text comes from the compiled declaration.')),
      ]},
    ],
  },
  {
    slug: 'mods/horloge', group: 'Créer un mod',
    title: t('Créer un outil avec une fenêtre et une horloge', 'Create a tool with a window and clock'),
    description: t('Un toolMod autonome, sans signal sélectionné : formulaire, événement, confirmation et changement de date.', 'A standalone toolMod with no selected signal: form, event, confirmation and date change.'),
    status: 'experimental',
    sections: [
      {id:'fenetre',title:t('Ouvrir un outil indépendant des signaux', 'Open a tool independently of signals'),blocks:[
        code('package nimby.mod\n\nimport nimby.*\n\nfun createMod() = toolMod(modInfo) {\n    metadata(author = "Your name", description = "Read the game clock.")\n    window("clock", "Clock", shortcut = "Ctrl+Shift+T") { event ->\n        showWindow(event, clock().dateTime().toString(),\n            listOf(ToolButton("refresh", "Refresh")))\n    }\n}', t('Outil complet en lecture seule', 'Complete read-only tool')),
        text(t('Préparez le projet avec le guide d’installation : mod.json génère modInfo. Cet outil ne déclare ni signal ni texture. Une partie doit être chargée et observée. Le raccourci ouvre une fenêtre Windows possédée par la fenêtre du jeu ; ce n’est pas un bouton dans sa barre d’outils. La croix ferme la fenêtre, pas le mod.', 'Prepare the project with the installation guide: mod.json generates modInfo. This tool declares no signal or texture. A game must be loaded and observed. The shortcut opens a Windows window owned by the game window; it is not a button on the game’s toolbar. Closing the window does not stop the mod.')),
        table([t('Déclaration', 'Declaration'),t('Rôle exact', 'Exact purpose')],[
          [literal('window(id, title, shortcut, handler)'),t('id identifie la fenêtre ; title est son titre visible et accepte tr ; shortcut vaut F8 par défaut. Jusqu’à 8 fenêtres, identifiants et raccourcis distincts.', 'id identifies the window; title is its visible caption and accepts tr; shortcut defaults to F8. Up to 8 windows, with distinct IDs and shortcuts.')],
          [literal('Ctrl+Shift+A … Ctrl+Shift+Z · F1 … F12'),t('Raccourcis Windows disponibles. Le SDK ouvre l’outil seulement quand le jeu est au premier plan. Un conflit de raccourci est signalé dans le journal.', 'Supported Windows shortcuts. The SDK opens the tool only while the game is in the foreground. Shortcut conflicts are reported in the log.')],
          [literal('ToolWindowEvent'),t('window identifie la fenêtre, action vaut open à l’ouverture puis l’id du bouton, values contient tous les champs entiers. sequence, worldId et generation identifient la demande et la partie.', 'window identifies the window; action is open on opening and then the button ID; values contains all integer fields. sequence, worldId and generation identify the request and game session.')],
          [literal('showWindow(event, message, buttons, inputs)'),t('message au-dessus, puis les champs et boutons. 8 champs et 12 boutons maximum. id reste technique, label est visible ; enabled active ou désactive le contrôle. Le formulaire UTF-8 complet est borné à 8192 octets.', 'message appears above the fields and buttons. At most 8 fields and 12 buttons. id is internal, label is visible, and enabled enables or disables the control. The complete UTF-8 form is limited to 8192 bytes.')],
        ]),
        text(t('Les champs numériques acceptent la saisie, l’effacement et le collage. Au clic, toutes les valeurs doivent respecter leurs bornes ; le SDK émet alors un événement unique avec le formulaire complet. Il n’émet pas un événement par touche. Le callback s’exécute sur le worker du mod, sans accès au thread d’affichage. Une perte de partie masque les fenêtres et invalide les événements.', 'Integer fields support typing, deletion and pasting. On a button click, every value must satisfy its bounds; the SDK then emits one event with the complete form. It does not emit an event for each keystroke. The callback runs on the mod worker, without access to the rendering thread. Losing the game session hides windows and invalidates events.')),
        text(t('Le titre, le message, les libellés de champs et les boutons acceptent tr. Une fenêtre déjà ouverte suit le changement de langue du jeu sans nouvel événement open : la saisie en cours, même vide, la sélection du texte et une demande en attente sont conservées. Seul un nouveau showWindow remplace le formulaire par les valeurs que votre mod fournit.', 'The title, message, field labels and buttons accept tr. An already open window follows game language changes without another open event: current input, even when empty, text selection and a pending request are preserved. Only a new showWindow replaces the form with the values supplied by your mod.')),
      ]},
      {id:'calendrier',title:t('Lire et modifier le calendrier', 'Read and change the calendar'),blocks:[
        table([t('Fonction ou type', 'Function or type'),t('Contrat', 'Contract')],[
          [literal('clock(): ToolClock'),t('Observation fraîche de la partie courante : utcSeconds est une date Unix en secondes ; elapsedMillis est le temps simulé écoulé en millisecondes. Cette lecture ne capture pas tout le réseau.', 'Fresh observation of the current session: utcSeconds is a Unix date in seconds; elapsedMillis is elapsed simulation time in milliseconds. This operation does not capture the entire network.')],
          [literal('GameDateTime · ToolClock.dateTime()'),t('Calendrier grégorien UTC, années 1 à 9999, mois 1 à 12. Les jours impossibles sont refusés. Aucun fuseau Windows ni décalage visuel du jeu n’est ajouté. toUtcSeconds et fromUtcSeconds convertissent sans écrire dans le jeu.', 'UTC Gregorian calendar, years 1 to 9999 and months 1 to 12. Impossible dates are rejected. No Windows timezone or game display offset is added. toUtcSeconds and fromUtcSeconds convert without writing to the game.')],
          [literal('changeTime(utcSeconds, recalculateTrains = false)'),t('Applique la date au point de mise à jour natif prévu. Sans recalcul, conserve les positions et translate les échéances relatives. Cela ne simule pas les journées sautées. Les fractions de seconde sont conservées.', 'Applies the date at the designated native update point. Without recalculation, it preserves positions and shifts relative deadlines. Skipped days are not simulated. Fractions of a second are preserved.')],
          [literal('recalculateTrains = true'),t('Demande en plus les interventions natives sur les trains. Elles peuvent déplacer les trains et coûter de l’argent. Ce choix doit être explicite dans votre interface.', 'Also requests native interventions on trains. They may move trains and cost money. This choice must be explicit in your interface.')],
          [literal('ToolTimeChange(clock, interventions)'),t('Horloge retournée après application et nombre d’interventions natives. Une erreur ou un délai dépassé n’est pas une preuve qu’aucun effet n’a eu lieu.', 'Clock returned after application and count of native interventions. An error or timeout does not prove that no effect occurred.')],
        ]),
        code('val target = GameDateTime(2026, 9, 28, 12, 0, 0)\n// Call only after your own confirmation step.\nval result = changeTime(target.toUtcSeconds())\nlog("Applied UTC=${result.clock.dateTime()}; interventions=${result.interventions}")',t('Dans le callback de confirmation', 'Inside the confirmation callback')),
        text(t('Time Change propose un seul mode : le changement avec interventions natives sur les trains, qui peuvent les déplacer et entraîner des coûts. Son flux est : lire, saisir six champs, afficher les effets, confirmer une seule fois, relire. Le SDK conserve aussi le mode sans intervention pour les autres outils. Le mod consomme la commande avant l’appel natif pour ne jamais la rejouer après une réponse incertaine. Conservez les données et la session de la confirmation, jamais le ToolContext. Remettez les confirmations à zéro à l’arrêt et au changement de partie.', 'Time Change offers one mode: changing time with native train interventions, which may move trains and incur costs. Its flow is: read, fill six fields, display the effects, confirm once, read again. The SDK also retains the mode without interventions for other tools. The mod consumes the command before the native call so it never replays it after an uncertain response. Keep confirmation data and session identity, never the ToolContext. Reset confirmations on stop and session changes.')),
        note(t('Les tests autonomes vérifient le calendrier, la confirmation, l’annulation, les événements périmés et l’absence de rejeu. Le formulaire et le changement d’heure dans une partie réelle restent à contrôler avant publication.', 'Standalone tests check the calendar, confirmation, cancellation, stale events and absence of replay. The form and time change in a real game still require validation before publishing.')),
        links({label:t('Préparer le projet', 'Prepare the project'),to:'/commencer/installation'}, {label:t('Tous les contrôles et leurs textes', 'All controls and their text'),to:'/mods/interface'}),
      ]},
    ],
  },
]
